Add Chuck Code for review
frempongdev/To-Do-List-Review pull request #1
Opened 2023-01-30 14:51 UTC by frempongdev

## In this PR 🔢 
I added the chuck of files from my previous To-Do-List project to be reviewed by my coding partner.

2023-02-03 08:05 UTC, chepkok3 requested changes
### ToDo List Review### 
@frempongdev Well done for the good work you have done. Everything looks impressive.
![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425615-8927e377-c543-407b-8da4-5c09fecc261b.gif)
✔️You have followed the GitHub flow very well. 
✔️There are no linter errors in your work and the repository has been professionally documented as required. 
👏🏿 👍🏿
1. [ ] However, despite all the functionalities working well and everything looking perfect, I think it would be better to introduce a delete button that appears when you click on the ellipsis-vertical icon as indicated in the minimalist demo image: 
<img width="842" alt="Screenshot 2023-01-30 at 18 40 50" src="https://user-images.githubusercontent.com/78428936/215523098-c1bb4f62-98ad-4405-b23a-7826f5a2ad04.png">

> You can achieve this by dynamically creating a button element with a function that enables deleting the item when the button thrash-can icon is pressed. 
2. [ ]  Generally, your project is good and meets all the requirements and quality. Great work 
![image](https://user-images.githubusercontent.com/78428936/215525547-5a5c6b23-ada8-400a-a76a-fe4890dcfb76.png)

2023-02-03 08:05 UTC, chepkok3 commented on README.md
> +<!-- <br>A massive Thank You to [Cindy Shin](https://www.behance.net/adagio07) who is the original designer of this [design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) -->
I think this was for the event project. Kindly remove it from the README.md file.

2023-02-03 09:42 UTC, frempongdev commented on README.md
> +<!-- <br>A massive Thank You to [Cindy Shin](https://www.behance.net/adagio07) who is the original designer of this [design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) -->
Alright , thanks You

2023-02-03 09:45 UTC, frempongdev commented
Thank you for pointing out the delete button issue, however, the functionality of the button is that it only appears when you are about to edit the task as shown in the demo. Kindly try clicking on the task field and notice that the menu button disappears and the delete button appears while the task becomes active to be edited.

2023-02-03 09:51 UTC, chepkok3 approved these changes
Hi @frempongdev 
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 👏👏👏

2023-02-03 10:38 UTC, merged

2023-04-02 23:36 UTC, frempongdev commented
Thanks @chepkok3 for approving this PR.